# Generated by Django 3.1.2 on 2020-12-01 15:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0003_interval_choices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='publication_date',
            field=models.CharField(blank=True, default='', max_length=255, verbose_name='publication date'),
        ),
        migrations.AlterField(
            model_name='scraper',
            name='checksum',
            field=models.CharField(blank=True, max_length=64, null=True, unique=True, verbose_name='checksum'),
        ),
    ]
