# Generated by Django 3.1.4 on 2020-12-04 11:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0005_thinktank_activatable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='monitor',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'activate', 'deactivate'), 'verbose_name': 'monitor', 'verbose_name_plural': 'monitors'},
        ),
        migrations.AlterModelOptions(
            name='scraper',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'activate', 'deactivate'), 'verbose_name': 'scraper', 'verbose_name_plural': 'scrapers'},
        ),
        migrations.AlterModelOptions(
            name='thinktank',
            options={'default_permissions': ('add', 'change', 'delete', 'view', 'activate', 'deactivate'), 'verbose_name': 'think tank', 'verbose_name_plural': 'think tanks'},
        ),
    ]
