# Generated by Django 3.1.4 on 2020-12-15 10:22

from django.db import migrations
import swp.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0006_basic_permissions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='type',
            field=swp.models.fields.ChoiceField(choices=[('list_with_docs', 'List with Documents')], db_index=True, default='list_with_docs', max_length=14, verbose_name='type'),
        ),
    ]
