# Generated by Django 3.1.4 on 2020-12-15 10:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0007_scraper_type'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ScraperType',
        ),
    ]
