# Generated by Django 3.1.4 on 2021-01-13 10:39

from django.db import migrations
import swp.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0009_scraper_index_last_run'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='type',
            field=swp.models.fields.ChoiceField(choices=[('list_with_link', 'List with Links'), ('list_with_link_and_doc', 'List with Links and Documents'), ('list_with_doc', 'List with Documents')], db_index=True, default='list_with_link', max_length=22, verbose_name='type'),
        ),
    ]
