# Generated by Django 3.1.4 on 2021-01-28 14:19

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0010_resolver_types'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), blank=True, null=True, size=None, verbose_name='authors'),
        ),
    ]
