# Generated by Django 3.1.4 on 2021-02-09 16:14

import django.contrib.postgres.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0013_monitor_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='monitor',
            name='recipients',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.EmailField(max_length=254), blank=True, size=None, verbose_name='recipients'),
        ),
    ]
