# Generated by Django 3.1.4 on 2021-02-11 14:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0014_monitor_optional_recipients'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='new_publication_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='new publication count'),
        ),
        migrations.AddField(
            model_name='monitor',
            name='publication_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='publication count'),
        ),
        migrations.AddField(
            model_name='thinktankfilter',
            name='new_publication_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='new publication count'),
        ),
        migrations.AddField(
            model_name='thinktankfilter',
            name='publication_count',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='publication count'),
        ),
    ]
