# Generated by Django 3.1.4 on 2021-01-19 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0018_scraper_last_modified'),
    ]

    operations = [
        migrations.AddField(
            model_name='scraper',
            name='is_running',
            field=models.BooleanField(default=False, editable=False, verbose_name='is running'),
        ),
    ]
