# Generated by Django 3.1.4 on 2021-03-10 12:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0020_monitor_last_access_always_set'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapererror',
            name='field',
            field=models.CharField(blank=True, max_length=50, verbose_name='field'),
        ),
        migrations.AddField(
            model_name='scrapererror',
            name='publication',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='errors', to='swp.publication', verbose_name='publication'),
        ),
    ]
