# Generated by Django 3.1.4 on 2021-03-12 12:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0021_scrapererror_publication_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapererror',
            name='level',
            field=models.CharField(choices=[('warning', 'Warning'), ('error', 'Error')], default='error', max_length=7, verbose_name='level'),
        ),
    ]
