# Generated by Django 3.1.4 on 2021-03-16 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0022_scrapererror_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='scrapererror',
            name='identifier',
            field=models.CharField(blank=True, max_length=255, verbose_name='identifier'),
        ),
    ]
