# Generated by Django 3.1.4 on 2021-03-19 11:44

from django.contrib.postgres.fields import ArrayField
from django.db import migrations, models

from swp.models.fields import ChoiceField
from swp.models.scraper import get_hash
from swp.models.thinktank import get_default_unique_fields


def migrate_unique_field(apps, schema_editor):
    Thinktank = apps.get_model('swp', 'ThinkTank')

    for thinktank in Thinktank.objects.all():
        thinktank.unique_fields = [thinktank.unique_field]
        thinktank.save(update_fields=['unique_fields'])


def migrate_hash(apps, schema_editor):
    Publication = apps.get_model('swp', 'Publication')

    for publication in Publication.objects.all():
        publication.hash = get_hash({
            field: getattr(publication, field, '')
            for field in publication.thinktank.unique_fields
        })
        publication.save(update_fields=['hash'])


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0023_scrapererror_identifier'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='hash'),
        ),
        migrations.AddField(
            model_name='thinktank',
            name='unique_fields',
            field=ArrayField(base_field=ChoiceField(choices=[('url', 'URL'), ('title', 'Title')], db_index=True, default='url', max_length=5), default=get_default_unique_fields, help_text="Defines which fields are used to uniquely identify a publication. This should generally always be `url`. However, if the think tank's publications are from a list without detail pages, then `title` may be appropriate in this exceptional case.", size=None, verbose_name='unique fields'),
        ),
        migrations.RunPython(code=migrate_unique_field),
        migrations.RunPython(code=migrate_hash, reverse_code=migrations.RunPython.noop),
        migrations.RemoveField(
            model_name='thinktank',
            name='unique_field',
        ),
    ]
