# Generated by Django 3.1.4 on 2021-03-17 16:20

from django.db import migrations
import swp.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0023_scrapererror_identifier'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scrapererror',
            name='level',
            field=swp.models.fields.ChoiceField(choices=[('warning', 'Warning'), ('error', 'Error')], db_index=True, default='error', max_length=7, verbose_name='level'),
        ),
    ]
