# Generated by Django 3.1.4 on 2021-03-19 11:44

import django.contrib.postgres.fields
from django.db import migrations, models
import swp.models.fields
import swp.models.thinktank


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0023_scrapererror_identifier'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinktank',
            name='unique_field',
        ),
        migrations.AddField(
            model_name='scraper',
            name='hash',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='hash'),
        ),
        migrations.AddField(
            model_name='thinktank',
            name='unique_fields',
            field=django.contrib.postgres.fields.ArrayField(base_field=swp.models.fields.ChoiceField(choices=[('url', 'URL'), ('title', 'Title')], db_index=True, default='url', max_length=5), default=swp.models.thinktank.get_default_unique_fields, size=None, verbose_name='unique fields'),
        ),
    ]
