# Generated by Django 3.1.4 on 2021-03-22 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0024_unique_fields'),
        ('swp', '0024_scrapererror_level_as_choicefield'),
    ]

    operations = [
    ]
