# Generated by Django 3.1.4 on 2021-03-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0025_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_error_recipient',
            field=models.BooleanField(default=False, verbose_name='is error recipient'),
        ),
    ]
