# Generated by Django 3.1.4 on 2021-03-25 17:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0029_split_scrapererror_identifier_in_title_and_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scrapererror',
            name='identifier',
        ),
    ]
