# Generated by Django 3.1.4 on 2021-03-26 10:06

from django.db import migrations, models
import swp.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0029_split_scrapererror_identifier_in_title_and_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='doi',
            field=models.CharField(blank=True, max_length=255, verbose_name='DOI'),
        ),
        migrations.AddField(
            model_name='publication',
            name='isbn',
            field=swp.models.fields.CombinedISBNField(blank=True, max_length=19, verbose_name='ISBN/ISSN'),
        ),
        migrations.AlterField(
            model_name='publicationfilter',
            name='field',
            field=swp.models.fields.ChoiceField(choices=[('title', 'Title'), ('subtitle', 'Subtitle'), ('abstract', 'Abstract'), ('authors', 'Authors'), ('publication_date', 'Publication Date'), ('url', 'URL'), ('pdf_url', 'PDF URL'), ('doi', 'DOI'), ('isbn', 'ISBN/ISSN'), ('tags', 'Tags')], db_index=True, default='title', max_length=16, verbose_name='field'),
        ),
    ]
