# Generated by Django 3.1.4 on 2021-04-12 09:34

import django.contrib.postgres.fields
from django.db import migrations, models


def migrate_value(apps, schema_editor):
    PublicationFilter = apps.get_model('swp', 'PublicationFilter')

    for filter in PublicationFilter.objects.all():
        filter.values = [filter.value]
        filter.save(update_fields=['values'])


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0030_publication_doi_and_isbn'),
    ]

    operations = [
        migrations.AddField(
            model_name='publicationfilter',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), null=True, size=None, verbose_name='values'),
        ),
        migrations.RunPython(code=migrate_value),
        migrations.RemoveField(
            model_name='publicationfilter',
            name='value',
        ),
        migrations.AlterField(
            model_name='publicationfilter',
            name='values',
            field=django.contrib.postgres.fields.ArrayField(base_field=models.CharField(max_length=255), size=None, verbose_name='values'),
        )
    ]
