# Generated by Django 3.1.4 on 2021-11-25 15:06

import django.contrib.postgres.fields
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import swp.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0034_monitor_tags_default_to_empty_list'),
    ]

    operations = [
        migrations.CreateModel(
            name='ZoteroTransfer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(max_length=255, verbose_name='api key')),
                ('path', models.CharField(max_length=255, verbose_name='path')),
                ('collection_keys', django.contrib.postgres.fields.ArrayField(base_field=swp.models.fields.ZoteroObjectKeyField(max_length=8), blank=True, default=list, size=None, verbose_name='collection keys')),
                ('version', models.IntegerField(default=0, editable=False, verbose_name='version')),
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('updated', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='updated')),
                ('last_transferred', models.DateTimeField(blank=True, null=True, verbose_name='transferred')),
                ('publication', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='zotero_transfers', to='swp.publication', verbose_name='publication')),
            ],
            options={
                'verbose_name': 'zotero transfer',
                'verbose_name_plural': 'zotero transfers',
                'unique_together': {('publication', 'api_key', 'path')},
            },
        ),
    ]
