# Generated by Django 3.1.4 on 2021-12-09 10:48

from django.db import migrations
import swp.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0035_zoterotransfer'),
    ]

    operations = [
        migrations.AddField(
            model_name='zoterotransfer',
            name='attachment_key',
            field=swp.models.fields.ZoteroObjectKeyField(blank=True, max_length=8, null=True, verbose_name='attachment key'),
        ),
        migrations.AddField(
            model_name='zoterotransfer',
            name='key',
            field=swp.models.fields.ZoteroObjectKeyField(blank=True, max_length=8, null=True, verbose_name='key'),
        ),
    ]
