# Generated by Django 3.1.4 on 2022-06-01 13:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0036_zotero_object_keys'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='last_publication_count_update',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last publication count update'),
        ),
        migrations.AddField(
            model_name='thinktankfilter',
            name='last_publication_count_update',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='last publication count update'),
        ),
    ]
