# Generated by Django 3.1.4 on 2022-11-07 14:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0037_add_last_publication_count_update'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='publication',
            options={
                'verbose_name': 'publication',
                'verbose_name_plural': 'publications',
                'permissions': [
                    ('can_research', 'Can use research interface'),
                ],
            },
        ),
    ]
