# Generated by Django 3.1.4 on 2022-11-09 11:44

from django.conf import settings
from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0038_publication_research_permission'),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicationList',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(default=timezone.now, editable=False, verbose_name='created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('name', models.CharField(max_length=100, verbose_name='Name')),
            ],
            options={
                'verbose_name': 'publication list',
                'verbose_name_plural': 'publication lists',
            },
        ),
        migrations.CreateModel(
            name='PublicationListEntry',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('created', models.DateTimeField(default=timezone.now, editable=False, verbose_name='created')),
                ('publication', models.ForeignKey(on_delete=models.CASCADE, related_name='+', to='swp.publication', verbose_name='publication list')),
                ('publication_list', models.ForeignKey(on_delete=models.CASCADE, related_name='entries', to='swp.publicationlist', verbose_name='publication list')),
            ],
            options={
                'verbose_name': 'publication list entry',
                'verbose_name_plural': 'publication list entries',
                'unique_together': [
                    ('publication_list', 'publication'),
                ],
            },
        ),
        migrations.AddField(
            model_name='publicationlist',
            name='publications',
            field=models.ManyToManyField(blank=True, through='swp.PublicationListEntry', to='swp.Publication', verbose_name='Publications'),
        ),
        migrations.AddField(
            model_name='publicationlist',
            name='user',
            field=models.ForeignKey(on_delete=models.CASCADE, related_name='publication_lists', to=settings.AUTH_USER_MODEL, verbose_name='user'),
        ),
        migrations.AlterUniqueTogether(
            name='publicationlist',
            unique_together=[
                ('user', 'name'),
            ],
        ),
    ]
