# Generated by Django 3.2.16 on 2023-12-05 11:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0040_pool'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='pools',
            field=models.ManyToManyField(blank=True, related_name='users', to='swp.Pool', verbose_name='pools'),
        ),
    ]
