# Generated by Django 3.2.16 on 2023-12-12 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0042_thinktank_domain'),
    ]

    operations = [
        migrations.AddField(
            model_name='monitor',
            name='pool',
            field=models.ForeignKey(default=0, on_delete=models.PROTECT, related_name='monitors', to='swp.pool', verbose_name='pool'),
            preserve_default=False,
        ),
    ]
