# Generated by Django 3.2.16 on 2023-12-14 09:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0044_monitor_query'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thinktankfilter',
            name='monitor',
        ),
        migrations.RemoveField(
            model_name='thinktankfilter',
            name='thinktank',
        ),
        migrations.DeleteModel(
            name='PublicationFilter',
        ),
        migrations.DeleteModel(
            name='ThinktankFilter',
        ),
    ]
