# Generated by Django 3.2.16 on 2023-12-14 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0045_remove_monitor_filters'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='monitor',
            constraint=models.CheckConstraint(
                check=models.Q(is_active=False) | ~models.Q(query=''),
                name='active_monitor_has_query',
            ),
        ),
    ]
