# Generated by Django 3.2.16 on 2024-02-06 14:04

from django.db import migrations, models
from django.utils import timezone


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0046_monitor_active_monitor_has_query'),
    ]

    operations = [
        migrations.AddField(
            model_name='ScraperError',
            name='sent',
            field=models.DateTimeField(editable=False, default=timezone.now, null=True, verbose_name='sent'),
            preserve_default=False,
        ),
    ]
