# Generated by Django 3.2.16 on 2024-03-01 13:50

from django.db import migrations

from swp.utils.migrations import AddRolePerm


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('swp', '0047_scrapererror_sent'),
    ]

    operations = [
        AddRolePerm('swp-editor', 'view_pool'),
    ]
