# Generated by Django 3.2.16 on 2024-03-01 13:50

from django.db import migrations

from swp.utils.migrations import get_queryset


def get_object(apps, schema_editor, app_label, model, **query):
    return get_queryset(apps, schema_editor, app_label, model).filter(**query).first()


def get_group(apps, schema_editor):
    return get_object(apps, schema_editor, 'auth', 'Group', name='swp-editor')


def get_permission(apps, schema_editor):
    return get_object(apps, schema_editor, 'auth', 'Permission', content_type__app_label='swp', codename='view_pool')


def get_objects(apps, schema_editor):
    return get_group(apps, schema_editor), get_permission(apps, schema_editor)


def add_pool_view_perm_to_editor_role(apps, schema_editor):
    group, permission = get_objects(apps, schema_editor)

    if group and permission:
        return group.permissions.add(permission)


def remove_pool_view_perm_from_editor_role(apps, schema_editor):
    group, permission = get_objects(apps, schema_editor)

    if group and permission:
        return group.permissions.remove(permission)


class Migration(migrations.Migration):

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('swp', '0047_scrapererror_sent'),
    ]

    operations = [
        migrations.RunPython(
            code=add_pool_view_perm_to_editor_role,
            reverse_code=remove_pool_view_perm_from_editor_role,
        ),
    ]
