# Generated by Django 3.2.16 on 2024-03-27 13:45

from django.contrib.postgres.indexes import GinIndex
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0049_add_can_research_perm_to_editor_role'),
    ]

    operations = [
        migrations.AlterField(
            model_name='zoterotransfer',
            name='api_key',
            field=models.CharField(db_index=True, max_length=255, verbose_name='api key'),
        ),
        migrations.AlterField(
            model_name='zoterotransfer',
            name='path',
            field=models.CharField(db_index=True, max_length=255, verbose_name='path'),
        ),
        migrations.AddIndex(
            model_name='zoterotransfer',
            index=GinIndex(fields=['collection_keys'], name='swp_zoterot_collect_3382bd_gin'),
        ),
        migrations.AddIndex(
            model_name='zoterotransfer',
            index=models.Index(models.Q(last_transferred__gte=models.F('updated')), name='transferred_after_updated_idx'),
        ),
    ]
