# Generated by Django 3.2.16 on 2024-06-20 08:49

from django.db import migrations

from swp.models.fields import CharArrayField


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0050_zotero_transfer_indices'),
    ]

    operations = [
        migrations.AlterField(
            model_name='publication',
            name='authors',
            field=CharArrayField(blank=True, max_length=255, null=True, size=None, verbose_name='authors'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='tags',
            field=CharArrayField(blank=True, default=list, max_length=255, size=None, verbose_name='tags'),
        ),
    ]
