# Generated by Django 4.1.13 on 2024-12-10 10:34

from django.db import migrations, models

from swp.utils.migrations import get_queryset


def set_publication_date_clean(apps, schema_editor):
    get_queryset(apps, schema_editor, 'swp', 'Publication').update(
        publication_date_clean=models.F('created'),
    )


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0054_publication_embedding'),
    ]

    operations = [
        migrations.AddField(
            model_name='Publication',
            name='publication_date_clean',
            field=models.DateField(blank=True, null=True, verbose_name='publication date (clean)'),
        ),
        migrations.RunPython(
            code=set_publication_date_clean,
            reverse_code=migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='Publication',
            name='publication_date_clean',
            field=models.DateField(blank=True, verbose_name='publication date (clean)'),
        ),
    ]
