# Generated by Django 4.1.13 on 2024-12-10 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0055_publication_date_clean'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='last_pollux_fetch',
            field=models.DateTimeField(editable=False, null=True, verbose_name='last pollux fetch'),
        ),
        migrations.AddField(
            model_name='publication',
            name='last_pollux_update',
            field=models.DateTimeField(editable=False, null=True, verbose_name='last pollux update'),
        ),
    ]
