# Generated by Django 4.1.13 on 2025-01-14 20:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0056_publication_pollux_timestamps'),
    ]

    operations = [
        migrations.AddField(
            model_name='publication',
            name='last_pollux_schedule',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='last pollux schedule'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='last_pollux_fetch',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='last pollux fetch'),
        ),
        migrations.AlterField(
            model_name='publication',
            name='last_pollux_update',
            field=models.DateTimeField(db_index=True, editable=False, null=True, verbose_name='last pollux update'),
        ),
    ]
