# Generated by Django 4.1.13 on 2025-11-05 10:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0057_publication_last_pollux_schedule_and_indices'),
    ]

    operations = [
        migrations.CreateModel(
            name='AuthToken',
            fields=[
                ('created', models.DateTimeField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('last_modified', models.DateTimeField(auto_now=True, verbose_name='last modified')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, related_name='auth_token', serialize=False, to=settings.AUTH_USER_MODEL, verbose_name='user')),
                ('key', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='key')),
                ('expires', models.DateTimeField(blank=True, null=True, verbose_name='expires')),
            ],
            options={
                'verbose_name': 'auth token',
                'verbose_name_plural': 'auth tokens',
            },
        ),
    ]
