# Generated by Django 4.1.13 on 2025-11-05 11:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0058_authtoken'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='thinktank',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='scrapers', to='swp.thinktank', verbose_name='think tank'),
        ),
    ]
