# Generated by Django 4.1.13 on 2025-11-12 11:31

from django.db import migrations

from swp.models.fields import LongURLField


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0059_alter_scraper_thinktank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scraper',
            name='start_url',
            field=LongURLField(help_text="Must match or be a subdomain of its think tank's domain.", max_length=1024, verbose_name='start URL'),
        ),
    ]
