# Generated by Django 4.1.13 on 2025-11-12 14:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('swp', '0060_alter_scraper_start_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='scraper',
            name='checksum',
        ),
    ]
