name: staging deployment

on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
    - name: deploy to staging
      uses: appleboy/ssh-action@master
      with:
        proxy_host: ${{ secrets.PROXY_HOST }}
        proxy_port: 6589
        proxy_username: ci
        proxy_key: ${{ secrets.DEPLOYMENT_KEY }}
        host: 10.1.0.4
        username: ci
        key: ${{ secrets.DEPLOYMENT_KEY }}
        port: 6589
        script: |
          whoami
          ls -al
          pwd
